### ISSUE TITLE
Content is Identical to Box Styles Codealong

### ISSUE THREAD

**Issue by JVThomas** [learn-co-curriculum/box-styles#2]
I just started Box Styles on Learn and that has two sections, Box Styles and Box Styles Codealong.
The Box Styles page  consists of an embedded youtube video that plays a Box Style Codealong. The next lesson after, Box Style Codealong, has the same embedded video. The only difference between the two sections is that the codealong section has you forking the repo and submitting the pull request. In terms of content, they’re identical. Im guessing this isn't intentional?
![box-styles](https://cloud.githubusercontent.com/assets/6664778/11151406/fb780eb2-89fa-11e5-814d-00f464666bc3.png)
![box-styles-codealong](https://cloud.githubusercontent.com/assets/6664778/11151409/fdbfe5c8-89fa-11e5-9b39-f9319e61e3c6.png)

**Comment by AnnJohn** [comment]
thanks for raising the issue! we'll remove the first lesson.
